/**
 * index.js — React Native entry point
 * REQUIRED: This file must exist in repo root for "react-native bundle" to work.
 *
 * FIX: Removed `import { name as appName } from './app.json'`
 * app.json is generated by the RN scaffold during CI (not committed to repo),
 * so importing it here causes the JS bundler to fail with "module not found".
 * The app name is hardcoded to match the scaffold name set in the workflow.
 */
import { AppRegistry } from 'react-native';
import App from './App';

// Must match the name passed to `react-native init` in the workflow (NetShareBuild)
AppRegistry.registerComponent('NetShareBuild', () => App);
